### ISSUE TITLE
Installation guide?

### ISSUE THREAD

**Issue by BhaturaGuy** [TheCactusVert/mpv-sponsorblock#4]
for windows?

**Comment by TheCactusVert** [comment]
Plugin using the C API are only available on Linux/BSD platforms as specified by MPV doc : https://mpv.io/manual/stable/#c-plugins.

**Comment by Coool** [comment]
For Android?

**Comment by brian6932** [comment]
I was able to get this to build for Windows, moved the `dll` and `toml` files to their right paths, and even reproduced #21. However, I don't see any chapters or requests being made, nor `time-pos` getting moved. @TheCactusVert Any idea what could be going wrong?

https://github.com/TheCactusVert/mpv-client doesn't build on Windows:
<details>
 <summary>build logs</summary>

  ```
  ❯ cargo build --release --locked
     Compiling glob v0.3.1
     Compiling prettyplease v0.2.21
     Compiling libc v0.2.158
     Compiling memchr v2.7.4
     Compiling regex-syntax v0.8.4
     Compiling minimal-lexical v0.2.1
     Compiling windows_x86_64_msvc v0.52.6
     Compiling either v1.13.0
     Compiling bindgen v0.70.1
     Compiling rustc-hash v1.1.0
     Compiling bitflags v2.6.0
     Compiling log v0.4.22
     Compiling syn v2.0.76
     Compiling windows-targets v0.52.6
     Compiling itertools v0.13.0
     Compiling clang-sys v1.8.1
     Compiling nom v7.1.3
     Compiling libloading v0.8.5
     Compiling regex-automata v0.4.7
     Compiling cexpr v0.6.0
     Compiling regex v1.10.6
     Compiling serde_derive v1.0.209
     Compiling tokio-macros v2.4.0
     Compiling pin-project-internal v1.1.5
     Compiling tokio v1.39.3
     Compiling pin-project v1.1.5
     Compiling mpv-client-sys v1.0.1
     Compiling serde v1.0.209
  error: failed to run custom build command for `mpv-client-sys v1.0.1`
  
  Caused by:
    process didn't exit successfully: `~\src\github.com\TheCactusVert\mpv-sponsorblock\target\release\build\mpv-client-sys-3ee0231acaff655f\build-script-build` (exit code: 101)
    --- stderr
    wrapper.h:1:10: fatal error: 'mpv/client.h' file not found
  
    thread 'main' (14100) panicked at <redacted>:0:0:
    Unable to generate bindings: ClangDiagnostic("wrapper.h:1:10: fatal error: 'mpv/client.h' file not found\n")
    stack backtrace:
       0:     0x7ff6075fe0e0 - std::backtrace_rs::backtrace::win64::trace
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\..\..\backtrace\src\backtrace\win64.rs:85
       1:     0x7ff6075fe0e0 - std::backtrace_rs::backtrace::trace_unsynchronized
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
       2:     0x7ff6075fe0e0 - std::sys::backtrace::_print_fmt
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\sys\backtrace.rs:74
       3:     0x7ff6075fe0e0 - std::sys::backtrace::impl$0::print::impl$0::fmt
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\sys\backtrace.rs:44
       4:     0x7ff60760e961 - core::fmt::write
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\core\src\fmt\mod.rs:0
       5:     0x7ff607602964 - std::io::default_write_fmt
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\io\mod.rs:639
       6:     0x7ff607602964 - std::io::Write::write_fmt<std::sys::stdio::windows::Stderr>
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\io\mod.rs:1994
       7:     0x7ff6075e8072 - std::sys::backtrace::BacktraceLock::print
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\sys\backtrace.rs:47
       8:     0x7ff6075e8072 - std::panicking::default_hook::closure$0
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\panicking.rs:292
       9:     0x7ff6075f7faf - std::panicking::default_hook
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\panicking.rs:319
      10:     0x7ff6075f8263 - std::panicking::panic_with_hook
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\panicking.rs:825
      11:     0x7ff6075e8144 - std::panicking::panic_handler::closure$0
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\panicking.rs:698
      12:     0x7ff6075e638f - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::panic_handler::closure_env$0,never$>
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\sys\backtrace.rs:182
      13:     0x7ff6075e897e - std::panicking::panic_handler
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\panicking.rs:689
      14:     0x7ff60761999d - core::panicking::panic_fmt
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\core\src\panicking.rs:80
      15:     0x7ff607619767 - core::result::unwrap_failed
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\core\src\result.rs:1867
      16:     0x7ff607091bda - enum2$<core::result::Result<bindgen::Bindings,enum2$<bindgen::BindgenError> > >::expect<bindgen::Bindings,enum2$<bindgen::BindgenError> >
                                   at ~\scoop\persist\rustup-msvc\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:1185
      17:     0x7ff60709174e - build_script_build::main
                                   at ~\scoop\persist\rustup-msvc\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\mpv-client-sys-1.0.1\build.rs:8
      18:     0x7ff607092c0b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                                   at ~\scoop\persist\rustup-msvc\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:250
      19:     0x7ff60709166e - std::sys::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                                   at ~\scoop\persist\rustup-msvc\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\backtrace.rs:166
      20:     0x7ff607091691 - std::rt::lang_start::closure$0<tuple$<> >
                                   at ~\scoop\persist\rustup-msvc\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:206
      21:     0x7ff6075f6fa0 - std::rt::lang_start_internal::closure$0
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\rt.rs:175
      22:     0x7ff6075f6fa0 - std::panicking::catch_unwind::do_call
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\panicking.rs:581
      23:     0x7ff6075f6fa0 - std::panicking::catch_unwind
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\panicking.rs:544
      24:     0x7ff6075f6fa0 - std::panic::catch_unwind
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\panic.rs:359
      25:     0x7ff6075f6fa0 - std::rt::lang_start_internal
                                   at /rustc/38c0de8dcb14d42290042521be9958d37f3fa390/library\std\src\rt.rs:171
      26:     0x7ff60709147a - std::rt::lang_start<tuple$<> >
                                   at ~\scoop\persist\rustup-msvc\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:205
      27:     0x7ff607092f89 - main
      28:     0x7ff6076169e0 - invoke_main
                                   at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
      29:     0x7ff6076169e0 - __scrt_common_main_seh
                                   at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
      30:     0x7ffd85797374 - BaseThreadInitThunk
      31:     0x7ffd8635cc91 - RtlUserThreadStart
  warning: build failed, waiting for other jobs to finish...
  ```
</details>

However, https://github.com/snylonue/mpv-client-dyn does:

<details>
 <summary>Here's my diff</summary>

  ```patch
  diff --git i/Cargo.lock w/Cargo.lock
  index 6916c18..75fc683 100644
  --- i/Cargo.lock
  +++ w/Cargo.lock
  @@ -1,6 +1,6 @@
   # This file is automatically @generated by Cargo.
   # It is not intended for manual editing.
  -version = 3
  +version = 4
   
   [[package]]
   name = "addr2line"
  @@ -114,26 +114,6 @@ version = "0.22.1"
   source = "registry+https://github.com/rust-lang/crates.io-index"
   checksum = "72b3254f16251a8381aa12e40e3c4d2f0199f8c6508fbecb9d91f575e0fbb8c6"
   
  -[[package]]
  -name = "bindgen"
  -version = "0.70.1"
  -source = "registry+https://github.com/rust-lang/crates.io-index"
  -checksum = "f49d8fed880d473ea71efb9bf597651e77201bdd4893efe54c9e5d65ae04ce6f"
  -dependencies = [
  - "bitflags",
  - "cexpr",
  - "clang-sys",
  - "itertools",
  - "log",
  - "prettyplease",
  - "proc-macro2",
  - "quote",
  - "regex",
  - "rustc-hash 1.1.0",
  - "shlex",
  - "syn",
  -]
  -
   [[package]]
   name = "bitflags"
   version = "2.6.0"
  @@ -176,32 +156,12 @@ dependencies = [
    "shlex",
   ]
   
  -[[package]]
  -name = "cexpr"
  -version = "0.6.0"
  -source = "registry+https://github.com/rust-lang/crates.io-index"
  -checksum = "6fac387a98bb7c37292057cffc56d62ecb629900026402633ae9160df93a8766"
  -dependencies = [
  - "nom",
  -]
  -
   [[package]]
   name = "cfg-if"
   version = "1.0.0"
   source = "registry+https://github.com/rust-lang/crates.io-index"
   checksum = "baf1de4339761588bc0619e3cbc0120ee582ebb74b53b4efbf79117bd2da40fd"
   
  -[[package]]
  -name = "clang-sys"
  -version = "1.8.1"
  -source = "registry+https://github.com/rust-lang/crates.io-index"
  -checksum = "0b023947811758c97c59bf9d1c188fd619ad4718dcaa767947df1cadb14f39f4"
  -dependencies = [
  - "glob",
  - "libc",
  - "libloading",
  -]
  -
   [[package]]
   name = "colorchoice"
   version = "1.0.2"
  @@ -273,12 +233,6 @@ dependencies = [
    "windows-sys 0.48.0",
   ]
   
  -[[package]]
  -name = "either"
  -version = "1.13.0"
  -source = "registry+https://github.com/rust-lang/crates.io-index"
  -checksum = "60b1af1c220855b6ceac025d3f6ecdd2b7c4894bfe9cd9bda4fbb4bc7c0d4cf0"
  -
   [[package]]
   name = "env_filter"
   version = "0.1.2"
  @@ -404,12 +358,6 @@ version = "0.29.0"
   source = "registry+https://github.com/rust-lang/crates.io-index"
   checksum = "40ecd4077b5ae9fd2e9e169b102c6c330d0605168eb0e8bf79952b256dbefffd"
   
  -[[package]]
  -name = "glob"
  -version = "0.3.1"
  -source = "registry+https://github.com/rust-lang/crates.io-index"
  -checksum = "d2fabcfbdc87f4758337ca535fb41a6d701b65693ce38287d856d1674551ec9b"
  -
   [[package]]
   name = "hashbrown"
   version = "0.14.5"
  @@ -566,15 +514,6 @@ version = "1.70.1"
   source = "registry+https://github.com/rust-lang/crates.io-index"
   checksum = "7943c866cc5cd64cbc25b2e01621d07fa8eb2a1a23160ee81ce38704e97b8ecf"
   
  -[[package]]
  -name = "itertools"
  -version = "0.13.0"
  -source = "registry+https://github.com/rust-lang/crates.io-index"
  -checksum = "413ee7dfc52ee1a4949ceeb7dbc8a33f2d6c088194d9f922fb8318faf1f01186"
  -dependencies = [
  - "either",
  -]
  -
   [[package]]
   name = "itoa"
   version = "1.0.11"
  @@ -634,12 +573,6 @@ version = "0.3.17"
   source = "registry+https://github.com/rust-lang/crates.io-index"
   checksum = "6877bb514081ee2a7ff5ef9de3281f14a4dd4bceac4c09388074a6b5df8a139a"
   
  -[[package]]
  -name = "minimal-lexical"
  -version = "0.2.1"
  -source = "registry+https://github.com/rust-lang/crates.io-index"
  -checksum = "68354c5c6bd36d73ff3feceb05efa59b6acb7626617f4962be322a825e61f79a"
  -
   [[package]]
   name = "miniz_oxide"
   version = "0.7.4"
  @@ -662,21 +595,13 @@ dependencies = [
   ]
   
   [[package]]
  -name = "mpv-client"
  -version = "1.0.1"
  -source = "registry+https://github.com/rust-lang/crates.io-index"
  -checksum = "60a131cb5edb5564cfb55a02f53f9a6a6ed3f5b28a4e13e682a74e1c47dd1c17"
  -dependencies = [
  - "mpv-client-sys",
  -]
  -
  -[[package]]
  -name = "mpv-client-sys"
  -version = "1.0.1"
  +name = "mpv-client-dyn"
  +version = "0.5.0"
   source = "registry+https://github.com/rust-lang/crates.io-index"
  -checksum = "39c0d45bb600e29318acb024e92e03c12ce78cf9530eaaa8f5a98dca4f54f8c6"
  +checksum = "4e0de0454593addc7e2ffaa7fc5a421b345c005abdb2edd14cd06ff43ab91319"
   dependencies = [
  - "bindgen",
  + "libloading",
  + "once_cell",
   ]
   
   [[package]]
  @@ -687,7 +612,7 @@ dependencies = [
    "dirs",
    "env_logger",
    "log",
  - "mpv-client",
  + "mpv-client-dyn",
    "regex",
    "serde",
    "serde_derive",
  @@ -697,16 +622,6 @@ dependencies = [
    "url",
   ]
   
  -[[package]]
  -name = "nom"
  -version = "7.1.3"
  -source = "registry+https://github.com/rust-lang/crates.io-index"
  -checksum = "d273983c5a657a70a3e8f2a01329822f3b8c8172b73826411a55751e404a0a4a"
  -dependencies = [
  - "memchr",
  - "minimal-lexical",
  -]
  -
   [[package]]
   name = "object"
   version = "0.36.3"
  @@ -781,16 +696,6 @@ dependencies = [
    "zerocopy",
   ]
   
  -[[package]]
  -name = "prettyplease"
  -version = "0.2.21"
  -source = "registry+https://github.com/rust-lang/crates.io-index"
  -checksum = "a909e6e8053fa1a5ad670f5816c7d93029ee1fa8898718490544a6b0d5d38b3e"
  -dependencies = [
  - "proc-macro2",
  - "syn",
  -]
  -
   [[package]]
   name = "proc-macro2"
   version = "1.0.86"
  @@ -810,7 +715,7 @@ dependencies = [
    "pin-project-lite",
    "quinn-proto",
    "quinn-udp",
  - "rustc-hash 2.0.0",
  + "rustc-hash",
    "rustls",
    "socket2",
    "thiserror",
  @@ -827,7 +732,7 @@ dependencies = [
    "bytes",
    "rand",
    "ring",
  - "rustc-hash 2.0.0",
  + "rustc-hash",
    "rustls",
    "slab",
    "thiserror",
  @@ -990,12 +895,6 @@ version = "0.1.24"
   source = "registry+https://github.com/rust-lang/crates.io-index"
   checksum = "719b953e2095829ee67db738b3bfa9fa368c94900df327b3f07fe6e794d2fe1f"
   
  -[[package]]
  -name = "rustc-hash"
  -version = "1.1.0"
  -source = "registry+https://github.com/rust-lang/crates.io-index"
  -checksum = "08d43f7aa6b08d49f382cde6a7982047c3426db949b1424bc4b7ec9ae12c6ce2"
  -
   [[package]]
   name = "rustc-hash"
   version = "2.0.0"
  diff --git i/Cargo.toml w/Cargo.toml
  index 980b313..f8f7fd0 100644
  --- i/Cargo.toml
  +++ w/Cargo.toml
  @@ -18,7 +18,7 @@ async-channel = "2.3.1"
   dirs = "5.0.1"
   env_logger = "0.11.5"
   log = "0.4.22"
  -mpv-client = "1.0.1"
  +mpv-client-dyn = "0.5.0"
   #mpv-client = { path = "../mpv-client/mpv-client" }
   #mpv-client = { git = "https://github.com/TheCactusVert/mpv-client.git", branch = "bindgen" }
   regex = "1.10.6"
  diff --git i/src/client/mod.rs w/src/client/mod.rs
  index e069f5d..a1cf920 100644
  --- i/src/client/mod.rs
  +++ w/src/client/mod.rs
  @@ -7,7 +7,7 @@ use std::sync::{Arc, Mutex};
   use std::time::Duration;
   
   use async_channel::Sender;
  -use mpv_client::{mpv_handle, osd, Client as MpvClient, ClientMessage, Event, Handle, Property, Result};
  +use mpv_client_dyn::{mpv_handle, osd, Client as MpvClient, ClientMessage, Event, Handle, Property, Result};
   use regex::Regex;
   use sponsorblock_client::*;
   use tokio::runtime::Runtime;
  @@ -21,6 +21,7 @@ static NAME_PROP_MUTE: &str = "mute";
   
   const REPL_PROP_TIME: u64 = 1;
   const REPL_PROP_MUTE: u64 = 2;
  +const MPV_FORMAT: i32 = 1;
   
   macro_rules! osd_info {
       ($client:expr, $duration:expr, $($arg:tt)*) => {
  @@ -308,8 +309,8 @@ impl Client {
           // The plugin is disabled and user allow plugin to run nad segments are fetched
           if !self.is_enabled && self.user_toggle && self.fetched() {
               self.is_enabled = true;
  -            self.observe_property::<f64>(REPL_PROP_TIME, NAME_PROP_TIME)?;
  -            self.observe_property::<bool>(REPL_PROP_MUTE, NAME_PROP_MUTE)?;
  +            self.observe_property(REPL_PROP_TIME, NAME_PROP_TIME, MPV_FORMAT)?;
  +            self.observe_property(REPL_PROP_MUTE, NAME_PROP_MUTE, MPV_FORMAT)?;
           }
           Ok(())
       }
  diff --git i/src/lib.rs w/src/lib.rs
  index b7c10ab..4d39f04 100644
  --- i/src/lib.rs
  +++ w/src/lib.rs
  @@ -1,7 +1,7 @@
   mod client;
   
   use client::Client;
  -use mpv_client::mpv_handle;
  +use mpv_client_dyn::mpv_handle;
   
   // MPV entry point
   #[no_mangle]
  
  ```
</details>


System Informer even shows the dll being loaded by the process:

![](https://github.com/user-attachments/assets/26f87353-62f8-4344-8b16-f12a2cff206a)
